// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exchange.proto

package currency;

public final class ExchangeOuterClass {
  private ExchangeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code currency.Currency}
   */
  public enum Currency
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>PLN = 0;</code>
     */
    PLN(0),
    /**
     * <code>EUR = 1;</code>
     */
    EUR(1),
    /**
     * <code>USD = 2;</code>
     */
    USD(2),
    /**
     * <code>GBP = 3;</code>
     */
    GBP(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>PLN = 0;</code>
     */
    public static final int PLN_VALUE = 0;
    /**
     * <code>EUR = 1;</code>
     */
    public static final int EUR_VALUE = 1;
    /**
     * <code>USD = 2;</code>
     */
    public static final int USD_VALUE = 2;
    /**
     * <code>GBP = 3;</code>
     */
    public static final int GBP_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Currency valueOf(int value) {
      return forNumber(value);
    }

    public static Currency forNumber(int value) {
      switch (value) {
        case 0: return PLN;
        case 1: return EUR;
        case 2: return USD;
        case 3: return GBP;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Currency>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Currency> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Currency>() {
            public Currency findValueByNumber(int number) {
              return Currency.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return currency.ExchangeOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final Currency[] VALUES = values();

    public static Currency valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Currency(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:currency.Currency)
  }

  public interface CurrencyRateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:currency.CurrencyRate)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.currency.Currency currency = 1;</code>
     */
    int getCurrencyValue();
    /**
     * <code>.currency.Currency currency = 1;</code>
     */
    currency.ExchangeOuterClass.Currency getCurrency();

    /**
     * <code>double rate = 2;</code>
     */
    double getRate();
  }
  /**
   * Protobuf type {@code currency.CurrencyRate}
   */
  public  static final class CurrencyRate extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:currency.CurrencyRate)
      CurrencyRateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CurrencyRate.newBuilder() to construct.
    private CurrencyRate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CurrencyRate() {
      currency_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CurrencyRate(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              currency_ = rawValue;
              break;
            }
            case 17: {

              rate_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return currency.ExchangeOuterClass.internal_static_currency_CurrencyRate_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return currency.ExchangeOuterClass.internal_static_currency_CurrencyRate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              currency.ExchangeOuterClass.CurrencyRate.class, currency.ExchangeOuterClass.CurrencyRate.Builder.class);
    }

    public static final int CURRENCY_FIELD_NUMBER = 1;
    private int currency_;
    /**
     * <code>.currency.Currency currency = 1;</code>
     */
    public int getCurrencyValue() {
      return currency_;
    }
    /**
     * <code>.currency.Currency currency = 1;</code>
     */
    public currency.ExchangeOuterClass.Currency getCurrency() {
      @SuppressWarnings("deprecation")
      currency.ExchangeOuterClass.Currency result = currency.ExchangeOuterClass.Currency.valueOf(currency_);
      return result == null ? currency.ExchangeOuterClass.Currency.UNRECOGNIZED : result;
    }

    public static final int RATE_FIELD_NUMBER = 2;
    private double rate_;
    /**
     * <code>double rate = 2;</code>
     */
    public double getRate() {
      return rate_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (currency_ != currency.ExchangeOuterClass.Currency.PLN.getNumber()) {
        output.writeEnum(1, currency_);
      }
      if (rate_ != 0D) {
        output.writeDouble(2, rate_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (currency_ != currency.ExchangeOuterClass.Currency.PLN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, currency_);
      }
      if (rate_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, rate_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof currency.ExchangeOuterClass.CurrencyRate)) {
        return super.equals(obj);
      }
      currency.ExchangeOuterClass.CurrencyRate other = (currency.ExchangeOuterClass.CurrencyRate) obj;

      if (currency_ != other.currency_) return false;
      if (java.lang.Double.doubleToLongBits(getRate())
          != java.lang.Double.doubleToLongBits(
              other.getRate())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CURRENCY_FIELD_NUMBER;
      hash = (53 * hash) + currency_;
      hash = (37 * hash) + RATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getRate()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static currency.ExchangeOuterClass.CurrencyRate parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static currency.ExchangeOuterClass.CurrencyRate parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static currency.ExchangeOuterClass.CurrencyRate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static currency.ExchangeOuterClass.CurrencyRate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static currency.ExchangeOuterClass.CurrencyRate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static currency.ExchangeOuterClass.CurrencyRate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static currency.ExchangeOuterClass.CurrencyRate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static currency.ExchangeOuterClass.CurrencyRate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static currency.ExchangeOuterClass.CurrencyRate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static currency.ExchangeOuterClass.CurrencyRate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static currency.ExchangeOuterClass.CurrencyRate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static currency.ExchangeOuterClass.CurrencyRate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(currency.ExchangeOuterClass.CurrencyRate prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code currency.CurrencyRate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:currency.CurrencyRate)
        currency.ExchangeOuterClass.CurrencyRateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return currency.ExchangeOuterClass.internal_static_currency_CurrencyRate_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return currency.ExchangeOuterClass.internal_static_currency_CurrencyRate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                currency.ExchangeOuterClass.CurrencyRate.class, currency.ExchangeOuterClass.CurrencyRate.Builder.class);
      }

      // Construct using currency.ExchangeOuterClass.CurrencyRate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        currency_ = 0;

        rate_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return currency.ExchangeOuterClass.internal_static_currency_CurrencyRate_descriptor;
      }

      @java.lang.Override
      public currency.ExchangeOuterClass.CurrencyRate getDefaultInstanceForType() {
        return currency.ExchangeOuterClass.CurrencyRate.getDefaultInstance();
      }

      @java.lang.Override
      public currency.ExchangeOuterClass.CurrencyRate build() {
        currency.ExchangeOuterClass.CurrencyRate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public currency.ExchangeOuterClass.CurrencyRate buildPartial() {
        currency.ExchangeOuterClass.CurrencyRate result = new currency.ExchangeOuterClass.CurrencyRate(this);
        result.currency_ = currency_;
        result.rate_ = rate_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof currency.ExchangeOuterClass.CurrencyRate) {
          return mergeFrom((currency.ExchangeOuterClass.CurrencyRate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(currency.ExchangeOuterClass.CurrencyRate other) {
        if (other == currency.ExchangeOuterClass.CurrencyRate.getDefaultInstance()) return this;
        if (other.currency_ != 0) {
          setCurrencyValue(other.getCurrencyValue());
        }
        if (other.getRate() != 0D) {
          setRate(other.getRate());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        currency.ExchangeOuterClass.CurrencyRate parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (currency.ExchangeOuterClass.CurrencyRate) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int currency_ = 0;
      /**
       * <code>.currency.Currency currency = 1;</code>
       */
      public int getCurrencyValue() {
        return currency_;
      }
      /**
       * <code>.currency.Currency currency = 1;</code>
       */
      public Builder setCurrencyValue(int value) {
        currency_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.currency.Currency currency = 1;</code>
       */
      public currency.ExchangeOuterClass.Currency getCurrency() {
        @SuppressWarnings("deprecation")
        currency.ExchangeOuterClass.Currency result = currency.ExchangeOuterClass.Currency.valueOf(currency_);
        return result == null ? currency.ExchangeOuterClass.Currency.UNRECOGNIZED : result;
      }
      /**
       * <code>.currency.Currency currency = 1;</code>
       */
      public Builder setCurrency(currency.ExchangeOuterClass.Currency value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        currency_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.currency.Currency currency = 1;</code>
       */
      public Builder clearCurrency() {
        
        currency_ = 0;
        onChanged();
        return this;
      }

      private double rate_ ;
      /**
       * <code>double rate = 2;</code>
       */
      public double getRate() {
        return rate_;
      }
      /**
       * <code>double rate = 2;</code>
       */
      public Builder setRate(double value) {
        
        rate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double rate = 2;</code>
       */
      public Builder clearRate() {
        
        rate_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:currency.CurrencyRate)
    }

    // @@protoc_insertion_point(class_scope:currency.CurrencyRate)
    private static final currency.ExchangeOuterClass.CurrencyRate DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new currency.ExchangeOuterClass.CurrencyRate();
    }

    public static currency.ExchangeOuterClass.CurrencyRate getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CurrencyRate>
        PARSER = new com.google.protobuf.AbstractParser<CurrencyRate>() {
      @java.lang.Override
      public CurrencyRate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CurrencyRate(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CurrencyRate> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CurrencyRate> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public currency.ExchangeOuterClass.CurrencyRate getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ExchangeRateRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:currency.ExchangeRateRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .currency.Currency currencies = 1;</code>
     */
    java.util.List<currency.ExchangeOuterClass.Currency> getCurrenciesList();
    /**
     * <code>repeated .currency.Currency currencies = 1;</code>
     */
    int getCurrenciesCount();
    /**
     * <code>repeated .currency.Currency currencies = 1;</code>
     */
    currency.ExchangeOuterClass.Currency getCurrencies(int index);
    /**
     * <code>repeated .currency.Currency currencies = 1;</code>
     */
    java.util.List<java.lang.Integer>
    getCurrenciesValueList();
    /**
     * <code>repeated .currency.Currency currencies = 1;</code>
     */
    int getCurrenciesValue(int index);
  }
  /**
   * Protobuf type {@code currency.ExchangeRateRequest}
   */
  public  static final class ExchangeRateRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:currency.ExchangeRateRequest)
      ExchangeRateRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ExchangeRateRequest.newBuilder() to construct.
    private ExchangeRateRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ExchangeRateRequest() {
      currencies_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ExchangeRateRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                currencies_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              currencies_.add(rawValue);
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int oldLimit = input.pushLimit(length);
              while(input.getBytesUntilLimit() > 0) {
                int rawValue = input.readEnum();
                if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                  currencies_ = new java.util.ArrayList<java.lang.Integer>();
                  mutable_bitField0_ |= 0x00000001;
                }
                currencies_.add(rawValue);
              }
              input.popLimit(oldLimit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          currencies_ = java.util.Collections.unmodifiableList(currencies_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return currency.ExchangeOuterClass.internal_static_currency_ExchangeRateRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return currency.ExchangeOuterClass.internal_static_currency_ExchangeRateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              currency.ExchangeOuterClass.ExchangeRateRequest.class, currency.ExchangeOuterClass.ExchangeRateRequest.Builder.class);
    }

    public static final int CURRENCIES_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> currencies_;
    private static final com.google.protobuf.Internal.ListAdapter.Converter<
        java.lang.Integer, currency.ExchangeOuterClass.Currency> currencies_converter_ =
            new com.google.protobuf.Internal.ListAdapter.Converter<
                java.lang.Integer, currency.ExchangeOuterClass.Currency>() {
              public currency.ExchangeOuterClass.Currency convert(java.lang.Integer from) {
                @SuppressWarnings("deprecation")
                currency.ExchangeOuterClass.Currency result = currency.ExchangeOuterClass.Currency.valueOf(from);
                return result == null ? currency.ExchangeOuterClass.Currency.UNRECOGNIZED : result;
              }
            };
    /**
     * <code>repeated .currency.Currency currencies = 1;</code>
     */
    public java.util.List<currency.ExchangeOuterClass.Currency> getCurrenciesList() {
      return new com.google.protobuf.Internal.ListAdapter<
          java.lang.Integer, currency.ExchangeOuterClass.Currency>(currencies_, currencies_converter_);
    }
    /**
     * <code>repeated .currency.Currency currencies = 1;</code>
     */
    public int getCurrenciesCount() {
      return currencies_.size();
    }
    /**
     * <code>repeated .currency.Currency currencies = 1;</code>
     */
    public currency.ExchangeOuterClass.Currency getCurrencies(int index) {
      return currencies_converter_.convert(currencies_.get(index));
    }
    /**
     * <code>repeated .currency.Currency currencies = 1;</code>
     */
    public java.util.List<java.lang.Integer>
    getCurrenciesValueList() {
      return currencies_;
    }
    /**
     * <code>repeated .currency.Currency currencies = 1;</code>
     */
    public int getCurrenciesValue(int index) {
      return currencies_.get(index);
    }
    private int currenciesMemoizedSerializedSize;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getCurrenciesList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(currenciesMemoizedSerializedSize);
      }
      for (int i = 0; i < currencies_.size(); i++) {
        output.writeEnumNoTag(currencies_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < currencies_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeEnumSizeNoTag(currencies_.get(i));
        }
        size += dataSize;
        if (!getCurrenciesList().isEmpty()) {  size += 1;
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(dataSize);
        }currenciesMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof currency.ExchangeOuterClass.ExchangeRateRequest)) {
        return super.equals(obj);
      }
      currency.ExchangeOuterClass.ExchangeRateRequest other = (currency.ExchangeOuterClass.ExchangeRateRequest) obj;

      if (!currencies_.equals(other.currencies_)) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getCurrenciesCount() > 0) {
        hash = (37 * hash) + CURRENCIES_FIELD_NUMBER;
        hash = (53 * hash) + currencies_.hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static currency.ExchangeOuterClass.ExchangeRateRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static currency.ExchangeOuterClass.ExchangeRateRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static currency.ExchangeOuterClass.ExchangeRateRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static currency.ExchangeOuterClass.ExchangeRateRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static currency.ExchangeOuterClass.ExchangeRateRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static currency.ExchangeOuterClass.ExchangeRateRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static currency.ExchangeOuterClass.ExchangeRateRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static currency.ExchangeOuterClass.ExchangeRateRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static currency.ExchangeOuterClass.ExchangeRateRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static currency.ExchangeOuterClass.ExchangeRateRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static currency.ExchangeOuterClass.ExchangeRateRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static currency.ExchangeOuterClass.ExchangeRateRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(currency.ExchangeOuterClass.ExchangeRateRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code currency.ExchangeRateRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:currency.ExchangeRateRequest)
        currency.ExchangeOuterClass.ExchangeRateRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return currency.ExchangeOuterClass.internal_static_currency_ExchangeRateRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return currency.ExchangeOuterClass.internal_static_currency_ExchangeRateRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                currency.ExchangeOuterClass.ExchangeRateRequest.class, currency.ExchangeOuterClass.ExchangeRateRequest.Builder.class);
      }

      // Construct using currency.ExchangeOuterClass.ExchangeRateRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        currencies_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return currency.ExchangeOuterClass.internal_static_currency_ExchangeRateRequest_descriptor;
      }

      @java.lang.Override
      public currency.ExchangeOuterClass.ExchangeRateRequest getDefaultInstanceForType() {
        return currency.ExchangeOuterClass.ExchangeRateRequest.getDefaultInstance();
      }

      @java.lang.Override
      public currency.ExchangeOuterClass.ExchangeRateRequest build() {
        currency.ExchangeOuterClass.ExchangeRateRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public currency.ExchangeOuterClass.ExchangeRateRequest buildPartial() {
        currency.ExchangeOuterClass.ExchangeRateRequest result = new currency.ExchangeOuterClass.ExchangeRateRequest(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          currencies_ = java.util.Collections.unmodifiableList(currencies_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.currencies_ = currencies_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof currency.ExchangeOuterClass.ExchangeRateRequest) {
          return mergeFrom((currency.ExchangeOuterClass.ExchangeRateRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(currency.ExchangeOuterClass.ExchangeRateRequest other) {
        if (other == currency.ExchangeOuterClass.ExchangeRateRequest.getDefaultInstance()) return this;
        if (!other.currencies_.isEmpty()) {
          if (currencies_.isEmpty()) {
            currencies_ = other.currencies_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCurrenciesIsMutable();
            currencies_.addAll(other.currencies_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        currency.ExchangeOuterClass.ExchangeRateRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (currency.ExchangeOuterClass.ExchangeRateRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Integer> currencies_ =
        java.util.Collections.emptyList();
      private void ensureCurrenciesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          currencies_ = new java.util.ArrayList<java.lang.Integer>(currencies_);
          bitField0_ |= 0x00000001;
        }
      }
      /**
       * <code>repeated .currency.Currency currencies = 1;</code>
       */
      public java.util.List<currency.ExchangeOuterClass.Currency> getCurrenciesList() {
        return new com.google.protobuf.Internal.ListAdapter<
            java.lang.Integer, currency.ExchangeOuterClass.Currency>(currencies_, currencies_converter_);
      }
      /**
       * <code>repeated .currency.Currency currencies = 1;</code>
       */
      public int getCurrenciesCount() {
        return currencies_.size();
      }
      /**
       * <code>repeated .currency.Currency currencies = 1;</code>
       */
      public currency.ExchangeOuterClass.Currency getCurrencies(int index) {
        return currencies_converter_.convert(currencies_.get(index));
      }
      /**
       * <code>repeated .currency.Currency currencies = 1;</code>
       */
      public Builder setCurrencies(
          int index, currency.ExchangeOuterClass.Currency value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCurrenciesIsMutable();
        currencies_.set(index, value.getNumber());
        onChanged();
        return this;
      }
      /**
       * <code>repeated .currency.Currency currencies = 1;</code>
       */
      public Builder addCurrencies(currency.ExchangeOuterClass.Currency value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCurrenciesIsMutable();
        currencies_.add(value.getNumber());
        onChanged();
        return this;
      }
      /**
       * <code>repeated .currency.Currency currencies = 1;</code>
       */
      public Builder addAllCurrencies(
          java.lang.Iterable<? extends currency.ExchangeOuterClass.Currency> values) {
        ensureCurrenciesIsMutable();
        for (currency.ExchangeOuterClass.Currency value : values) {
          currencies_.add(value.getNumber());
        }
        onChanged();
        return this;
      }
      /**
       * <code>repeated .currency.Currency currencies = 1;</code>
       */
      public Builder clearCurrencies() {
        currencies_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .currency.Currency currencies = 1;</code>
       */
      public java.util.List<java.lang.Integer>
      getCurrenciesValueList() {
        return java.util.Collections.unmodifiableList(currencies_);
      }
      /**
       * <code>repeated .currency.Currency currencies = 1;</code>
       */
      public int getCurrenciesValue(int index) {
        return currencies_.get(index);
      }
      /**
       * <code>repeated .currency.Currency currencies = 1;</code>
       */
      public Builder setCurrenciesValue(
          int index, int value) {
        ensureCurrenciesIsMutable();
        currencies_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .currency.Currency currencies = 1;</code>
       */
      public Builder addCurrenciesValue(int value) {
        ensureCurrenciesIsMutable();
        currencies_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .currency.Currency currencies = 1;</code>
       */
      public Builder addAllCurrenciesValue(
          java.lang.Iterable<java.lang.Integer> values) {
        ensureCurrenciesIsMutable();
        for (int value : values) {
          currencies_.add(value);
        }
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:currency.ExchangeRateRequest)
    }

    // @@protoc_insertion_point(class_scope:currency.ExchangeRateRequest)
    private static final currency.ExchangeOuterClass.ExchangeRateRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new currency.ExchangeOuterClass.ExchangeRateRequest();
    }

    public static currency.ExchangeOuterClass.ExchangeRateRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ExchangeRateRequest>
        PARSER = new com.google.protobuf.AbstractParser<ExchangeRateRequest>() {
      @java.lang.Override
      public ExchangeRateRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ExchangeRateRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ExchangeRateRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ExchangeRateRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public currency.ExchangeOuterClass.ExchangeRateRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ExchangeRateResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:currency.ExchangeRateResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .currency.CurrencyRate rates = 1;</code>
     */
    java.util.List<currency.ExchangeOuterClass.CurrencyRate> 
        getRatesList();
    /**
     * <code>repeated .currency.CurrencyRate rates = 1;</code>
     */
    currency.ExchangeOuterClass.CurrencyRate getRates(int index);
    /**
     * <code>repeated .currency.CurrencyRate rates = 1;</code>
     */
    int getRatesCount();
    /**
     * <code>repeated .currency.CurrencyRate rates = 1;</code>
     */
    java.util.List<? extends currency.ExchangeOuterClass.CurrencyRateOrBuilder> 
        getRatesOrBuilderList();
    /**
     * <code>repeated .currency.CurrencyRate rates = 1;</code>
     */
    currency.ExchangeOuterClass.CurrencyRateOrBuilder getRatesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code currency.ExchangeRateResponse}
   */
  public  static final class ExchangeRateResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:currency.ExchangeRateResponse)
      ExchangeRateResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ExchangeRateResponse.newBuilder() to construct.
    private ExchangeRateResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ExchangeRateResponse() {
      rates_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ExchangeRateResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                rates_ = new java.util.ArrayList<currency.ExchangeOuterClass.CurrencyRate>();
                mutable_bitField0_ |= 0x00000001;
              }
              rates_.add(
                  input.readMessage(currency.ExchangeOuterClass.CurrencyRate.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          rates_ = java.util.Collections.unmodifiableList(rates_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return currency.ExchangeOuterClass.internal_static_currency_ExchangeRateResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return currency.ExchangeOuterClass.internal_static_currency_ExchangeRateResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              currency.ExchangeOuterClass.ExchangeRateResponse.class, currency.ExchangeOuterClass.ExchangeRateResponse.Builder.class);
    }

    public static final int RATES_FIELD_NUMBER = 1;
    private java.util.List<currency.ExchangeOuterClass.CurrencyRate> rates_;
    /**
     * <code>repeated .currency.CurrencyRate rates = 1;</code>
     */
    public java.util.List<currency.ExchangeOuterClass.CurrencyRate> getRatesList() {
      return rates_;
    }
    /**
     * <code>repeated .currency.CurrencyRate rates = 1;</code>
     */
    public java.util.List<? extends currency.ExchangeOuterClass.CurrencyRateOrBuilder> 
        getRatesOrBuilderList() {
      return rates_;
    }
    /**
     * <code>repeated .currency.CurrencyRate rates = 1;</code>
     */
    public int getRatesCount() {
      return rates_.size();
    }
    /**
     * <code>repeated .currency.CurrencyRate rates = 1;</code>
     */
    public currency.ExchangeOuterClass.CurrencyRate getRates(int index) {
      return rates_.get(index);
    }
    /**
     * <code>repeated .currency.CurrencyRate rates = 1;</code>
     */
    public currency.ExchangeOuterClass.CurrencyRateOrBuilder getRatesOrBuilder(
        int index) {
      return rates_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < rates_.size(); i++) {
        output.writeMessage(1, rates_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < rates_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, rates_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof currency.ExchangeOuterClass.ExchangeRateResponse)) {
        return super.equals(obj);
      }
      currency.ExchangeOuterClass.ExchangeRateResponse other = (currency.ExchangeOuterClass.ExchangeRateResponse) obj;

      if (!getRatesList()
          .equals(other.getRatesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getRatesCount() > 0) {
        hash = (37 * hash) + RATES_FIELD_NUMBER;
        hash = (53 * hash) + getRatesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static currency.ExchangeOuterClass.ExchangeRateResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static currency.ExchangeOuterClass.ExchangeRateResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static currency.ExchangeOuterClass.ExchangeRateResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static currency.ExchangeOuterClass.ExchangeRateResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static currency.ExchangeOuterClass.ExchangeRateResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static currency.ExchangeOuterClass.ExchangeRateResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static currency.ExchangeOuterClass.ExchangeRateResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static currency.ExchangeOuterClass.ExchangeRateResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static currency.ExchangeOuterClass.ExchangeRateResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static currency.ExchangeOuterClass.ExchangeRateResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static currency.ExchangeOuterClass.ExchangeRateResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static currency.ExchangeOuterClass.ExchangeRateResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(currency.ExchangeOuterClass.ExchangeRateResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code currency.ExchangeRateResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:currency.ExchangeRateResponse)
        currency.ExchangeOuterClass.ExchangeRateResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return currency.ExchangeOuterClass.internal_static_currency_ExchangeRateResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return currency.ExchangeOuterClass.internal_static_currency_ExchangeRateResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                currency.ExchangeOuterClass.ExchangeRateResponse.class, currency.ExchangeOuterClass.ExchangeRateResponse.Builder.class);
      }

      // Construct using currency.ExchangeOuterClass.ExchangeRateResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRatesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (ratesBuilder_ == null) {
          rates_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ratesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return currency.ExchangeOuterClass.internal_static_currency_ExchangeRateResponse_descriptor;
      }

      @java.lang.Override
      public currency.ExchangeOuterClass.ExchangeRateResponse getDefaultInstanceForType() {
        return currency.ExchangeOuterClass.ExchangeRateResponse.getDefaultInstance();
      }

      @java.lang.Override
      public currency.ExchangeOuterClass.ExchangeRateResponse build() {
        currency.ExchangeOuterClass.ExchangeRateResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public currency.ExchangeOuterClass.ExchangeRateResponse buildPartial() {
        currency.ExchangeOuterClass.ExchangeRateResponse result = new currency.ExchangeOuterClass.ExchangeRateResponse(this);
        int from_bitField0_ = bitField0_;
        if (ratesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            rates_ = java.util.Collections.unmodifiableList(rates_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.rates_ = rates_;
        } else {
          result.rates_ = ratesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof currency.ExchangeOuterClass.ExchangeRateResponse) {
          return mergeFrom((currency.ExchangeOuterClass.ExchangeRateResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(currency.ExchangeOuterClass.ExchangeRateResponse other) {
        if (other == currency.ExchangeOuterClass.ExchangeRateResponse.getDefaultInstance()) return this;
        if (ratesBuilder_ == null) {
          if (!other.rates_.isEmpty()) {
            if (rates_.isEmpty()) {
              rates_ = other.rates_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRatesIsMutable();
              rates_.addAll(other.rates_);
            }
            onChanged();
          }
        } else {
          if (!other.rates_.isEmpty()) {
            if (ratesBuilder_.isEmpty()) {
              ratesBuilder_.dispose();
              ratesBuilder_ = null;
              rates_ = other.rates_;
              bitField0_ = (bitField0_ & ~0x00000001);
              ratesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRatesFieldBuilder() : null;
            } else {
              ratesBuilder_.addAllMessages(other.rates_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        currency.ExchangeOuterClass.ExchangeRateResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (currency.ExchangeOuterClass.ExchangeRateResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<currency.ExchangeOuterClass.CurrencyRate> rates_ =
        java.util.Collections.emptyList();
      private void ensureRatesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          rates_ = new java.util.ArrayList<currency.ExchangeOuterClass.CurrencyRate>(rates_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          currency.ExchangeOuterClass.CurrencyRate, currency.ExchangeOuterClass.CurrencyRate.Builder, currency.ExchangeOuterClass.CurrencyRateOrBuilder> ratesBuilder_;

      /**
       * <code>repeated .currency.CurrencyRate rates = 1;</code>
       */
      public java.util.List<currency.ExchangeOuterClass.CurrencyRate> getRatesList() {
        if (ratesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(rates_);
        } else {
          return ratesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .currency.CurrencyRate rates = 1;</code>
       */
      public int getRatesCount() {
        if (ratesBuilder_ == null) {
          return rates_.size();
        } else {
          return ratesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .currency.CurrencyRate rates = 1;</code>
       */
      public currency.ExchangeOuterClass.CurrencyRate getRates(int index) {
        if (ratesBuilder_ == null) {
          return rates_.get(index);
        } else {
          return ratesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .currency.CurrencyRate rates = 1;</code>
       */
      public Builder setRates(
          int index, currency.ExchangeOuterClass.CurrencyRate value) {
        if (ratesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRatesIsMutable();
          rates_.set(index, value);
          onChanged();
        } else {
          ratesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .currency.CurrencyRate rates = 1;</code>
       */
      public Builder setRates(
          int index, currency.ExchangeOuterClass.CurrencyRate.Builder builderForValue) {
        if (ratesBuilder_ == null) {
          ensureRatesIsMutable();
          rates_.set(index, builderForValue.build());
          onChanged();
        } else {
          ratesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .currency.CurrencyRate rates = 1;</code>
       */
      public Builder addRates(currency.ExchangeOuterClass.CurrencyRate value) {
        if (ratesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRatesIsMutable();
          rates_.add(value);
          onChanged();
        } else {
          ratesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .currency.CurrencyRate rates = 1;</code>
       */
      public Builder addRates(
          int index, currency.ExchangeOuterClass.CurrencyRate value) {
        if (ratesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRatesIsMutable();
          rates_.add(index, value);
          onChanged();
        } else {
          ratesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .currency.CurrencyRate rates = 1;</code>
       */
      public Builder addRates(
          currency.ExchangeOuterClass.CurrencyRate.Builder builderForValue) {
        if (ratesBuilder_ == null) {
          ensureRatesIsMutable();
          rates_.add(builderForValue.build());
          onChanged();
        } else {
          ratesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .currency.CurrencyRate rates = 1;</code>
       */
      public Builder addRates(
          int index, currency.ExchangeOuterClass.CurrencyRate.Builder builderForValue) {
        if (ratesBuilder_ == null) {
          ensureRatesIsMutable();
          rates_.add(index, builderForValue.build());
          onChanged();
        } else {
          ratesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .currency.CurrencyRate rates = 1;</code>
       */
      public Builder addAllRates(
          java.lang.Iterable<? extends currency.ExchangeOuterClass.CurrencyRate> values) {
        if (ratesBuilder_ == null) {
          ensureRatesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, rates_);
          onChanged();
        } else {
          ratesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .currency.CurrencyRate rates = 1;</code>
       */
      public Builder clearRates() {
        if (ratesBuilder_ == null) {
          rates_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          ratesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .currency.CurrencyRate rates = 1;</code>
       */
      public Builder removeRates(int index) {
        if (ratesBuilder_ == null) {
          ensureRatesIsMutable();
          rates_.remove(index);
          onChanged();
        } else {
          ratesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .currency.CurrencyRate rates = 1;</code>
       */
      public currency.ExchangeOuterClass.CurrencyRate.Builder getRatesBuilder(
          int index) {
        return getRatesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .currency.CurrencyRate rates = 1;</code>
       */
      public currency.ExchangeOuterClass.CurrencyRateOrBuilder getRatesOrBuilder(
          int index) {
        if (ratesBuilder_ == null) {
          return rates_.get(index);  } else {
          return ratesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .currency.CurrencyRate rates = 1;</code>
       */
      public java.util.List<? extends currency.ExchangeOuterClass.CurrencyRateOrBuilder> 
           getRatesOrBuilderList() {
        if (ratesBuilder_ != null) {
          return ratesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(rates_);
        }
      }
      /**
       * <code>repeated .currency.CurrencyRate rates = 1;</code>
       */
      public currency.ExchangeOuterClass.CurrencyRate.Builder addRatesBuilder() {
        return getRatesFieldBuilder().addBuilder(
            currency.ExchangeOuterClass.CurrencyRate.getDefaultInstance());
      }
      /**
       * <code>repeated .currency.CurrencyRate rates = 1;</code>
       */
      public currency.ExchangeOuterClass.CurrencyRate.Builder addRatesBuilder(
          int index) {
        return getRatesFieldBuilder().addBuilder(
            index, currency.ExchangeOuterClass.CurrencyRate.getDefaultInstance());
      }
      /**
       * <code>repeated .currency.CurrencyRate rates = 1;</code>
       */
      public java.util.List<currency.ExchangeOuterClass.CurrencyRate.Builder> 
           getRatesBuilderList() {
        return getRatesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          currency.ExchangeOuterClass.CurrencyRate, currency.ExchangeOuterClass.CurrencyRate.Builder, currency.ExchangeOuterClass.CurrencyRateOrBuilder> 
          getRatesFieldBuilder() {
        if (ratesBuilder_ == null) {
          ratesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              currency.ExchangeOuterClass.CurrencyRate, currency.ExchangeOuterClass.CurrencyRate.Builder, currency.ExchangeOuterClass.CurrencyRateOrBuilder>(
                  rates_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          rates_ = null;
        }
        return ratesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:currency.ExchangeRateResponse)
    }

    // @@protoc_insertion_point(class_scope:currency.ExchangeRateResponse)
    private static final currency.ExchangeOuterClass.ExchangeRateResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new currency.ExchangeOuterClass.ExchangeRateResponse();
    }

    public static currency.ExchangeOuterClass.ExchangeRateResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ExchangeRateResponse>
        PARSER = new com.google.protobuf.AbstractParser<ExchangeRateResponse>() {
      @java.lang.Override
      public ExchangeRateResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ExchangeRateResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ExchangeRateResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ExchangeRateResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public currency.ExchangeOuterClass.ExchangeRateResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_currency_CurrencyRate_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_currency_CurrencyRate_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_currency_ExchangeRateRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_currency_ExchangeRateRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_currency_ExchangeRateResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_currency_ExchangeRateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016exchange.proto\022\010currency\"B\n\014CurrencyRa" +
      "te\022$\n\010currency\030\001 \001(\0162\022.currency.Currency" +
      "\022\014\n\004rate\030\002 \001(\001\"=\n\023ExchangeRateRequest\022&\n" +
      "\ncurrencies\030\001 \003(\0162\022.currency.Currency\"=\n" +
      "\024ExchangeRateResponse\022%\n\005rates\030\001 \003(\0132\026.c" +
      "urrency.CurrencyRate*.\n\010Currency\022\007\n\003PLN\020" +
      "\000\022\007\n\003EUR\020\001\022\007\n\003USD\020\002\022\007\n\003GBP\020\0032\245\001\n\010Exchang" +
      "e\022O\n\014CurrentRates\022\035.currency.ExchangeRat" +
      "eRequest\032\036.currency.ExchangeRateResponse" +
      "\"\000\022H\n\013StreamRates\022\035.currency.ExchangeRat" +
      "eRequest\032\026.currency.CurrencyRate\"\0000\001b\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_currency_CurrencyRate_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_currency_CurrencyRate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_currency_CurrencyRate_descriptor,
        new java.lang.String[] { "Currency", "Rate", });
    internal_static_currency_ExchangeRateRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_currency_ExchangeRateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_currency_ExchangeRateRequest_descriptor,
        new java.lang.String[] { "Currencies", });
    internal_static_currency_ExchangeRateResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_currency_ExchangeRateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_currency_ExchangeRateResponse_descriptor,
        new java.lang.String[] { "Rates", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
