//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.2
//
// <auto-generated>
//
// Generated from file `bank.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Bank;

public class AuthData implements java.lang.Cloneable,
                                 java.io.Serializable
{
    public String pesel;

    public String uuid;

    public AuthData()
    {
        this.pesel = "";
        this.uuid = "";
    }

    public AuthData(String pesel, String uuid)
    {
        this.pesel = pesel;
        this.uuid = uuid;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        AuthData r = null;
        if(rhs instanceof AuthData)
        {
            r = (AuthData)rhs;
        }

        if(r != null)
        {
            if(this.pesel != r.pesel)
            {
                if(this.pesel == null || r.pesel == null || !this.pesel.equals(r.pesel))
                {
                    return false;
                }
            }
            if(this.uuid != r.uuid)
            {
                if(this.uuid == null || r.uuid == null || !this.uuid.equals(r.uuid))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::Bank::AuthData");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, pesel);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, uuid);
        return h_;
    }

    public AuthData clone()
    {
        AuthData c = null;
        try
        {
            c = (AuthData)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.pesel);
        ostr.writeString(this.uuid);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.pesel = istr.readString();
        this.uuid = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, AuthData v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public AuthData ice_read(com.zeroc.Ice.InputStream istr)
    {
        AuthData v = new AuthData();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<AuthData> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, AuthData v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<AuthData> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(AuthData.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final AuthData _nullMarshalValue = new AuthData();

    /** @hidden */
    public static final long serialVersionUID = -6995216369368243689L;
}
