//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.2
//
// <auto-generated>
//
// Generated from file `bank.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Bank;

public class ClientAlreadyExistsException extends com.zeroc.Ice.UserException
{
    public ClientAlreadyExistsException()
    {
        this.userData = new UserData();
    }

    public ClientAlreadyExistsException(Throwable cause)
    {
        super(cause);
        this.userData = new UserData();
    }

    public ClientAlreadyExistsException(UserData userData)
    {
        this.userData = userData;
    }

    public ClientAlreadyExistsException(UserData userData, Throwable cause)
    {
        super(cause);
        this.userData = userData;
    }

    public String ice_id()
    {
        return "::Bank::ClientAlreadyExistsException";
    }

    public UserData userData;

    /** @hidden */
    @Override
    protected void _writeImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice("::Bank::ClientAlreadyExistsException", -1, true);
        UserData.ice_write(ostr_, userData);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _readImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        userData = UserData.ice_read(istr_);
        istr_.endSlice();
    }

    /** @hidden */
    public static final long serialVersionUID = 4512000622974651907L;
}
