//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.2
//
// <auto-generated>
//
// Generated from file `bank.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Bank;

public class FailedAuthenticationException extends com.zeroc.Ice.UserException
{
    public FailedAuthenticationException()
    {
        this.authData = new AuthData();
        this.reason = "";
    }

    public FailedAuthenticationException(Throwable cause)
    {
        super(cause);
        this.authData = new AuthData();
        this.reason = "";
    }

    public FailedAuthenticationException(AuthData authData, String reason)
    {
        this.authData = authData;
        this.reason = reason;
    }

    public FailedAuthenticationException(AuthData authData, String reason, Throwable cause)
    {
        super(cause);
        this.authData = authData;
        this.reason = reason;
    }

    public String ice_id()
    {
        return "::Bank::FailedAuthenticationException";
    }

    public AuthData authData;

    public String reason;

    /** @hidden */
    @Override
    protected void _writeImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice("::Bank::FailedAuthenticationException", -1, true);
        AuthData.ice_write(ostr_, authData);
        ostr_.writeString(reason);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _readImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        authData = AuthData.ice_read(istr_);
        reason = istr_.readString();
        istr_.endSlice();
    }

    /** @hidden */
    public static final long serialVersionUID = 5148807659533728101L;
}
