//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.2
//
// <auto-generated>
//
// Generated from file `bank.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Bank;

public class InvalidLoanRequestException extends com.zeroc.Ice.UserException
{
    public InvalidLoanRequestException()
    {
        this.loanRequest = new LoanRequest();
        this.reason = "";
    }

    public InvalidLoanRequestException(Throwable cause)
    {
        super(cause);
        this.loanRequest = new LoanRequest();
        this.reason = "";
    }

    public InvalidLoanRequestException(LoanRequest loanRequest, String reason)
    {
        this.loanRequest = loanRequest;
        this.reason = reason;
    }

    public InvalidLoanRequestException(LoanRequest loanRequest, String reason, Throwable cause)
    {
        super(cause);
        this.loanRequest = loanRequest;
        this.reason = reason;
    }

    public String ice_id()
    {
        return "::Bank::InvalidLoanRequestException";
    }

    public LoanRequest loanRequest;

    public String reason;

    /** @hidden */
    @Override
    protected void _writeImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice("::Bank::InvalidLoanRequestException", -1, true);
        LoanRequest.ice_write(ostr_, loanRequest);
        ostr_.writeString(reason);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _readImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        loanRequest = LoanRequest.ice_read(istr_);
        reason = istr_.readString();
        istr_.endSlice();
    }

    /** @hidden */
    public static final long serialVersionUID = -4431170192063429041L;
}
