//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.2
//
// <auto-generated>
//
// Generated from file `bank.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Bank;

public class Period implements java.lang.Cloneable,
                               java.io.Serializable
{
    public int months;

    public Period()
    {
    }

    public Period(int months)
    {
        this.months = months;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Period r = null;
        if(rhs instanceof Period)
        {
            r = (Period)rhs;
        }

        if(r != null)
        {
            if(this.months != r.months)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::Bank::Period");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, months);
        return h_;
    }

    public Period clone()
    {
        Period c = null;
        try
        {
            c = (Period)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeInt(this.months);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.months = istr.readInt();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, Period v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public Period ice_read(com.zeroc.Ice.InputStream istr)
    {
        Period v = new Period();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Period> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, Period v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            ostr.writeSize(4);
            ice_write(ostr, v);
        }
    }

    static public java.util.Optional<Period> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            istr.skipSize();
            return java.util.Optional.of(Period.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final Period _nullMarshalValue = new Period();

    /** @hidden */
    public static final long serialVersionUID = 4938355718643452524L;
}
