//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.2
//
// <auto-generated>
//
// Generated from file `bank.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Bank;

public class UserData implements java.lang.Cloneable,
                                 java.io.Serializable
{
    public String pesel;

    public String uuid;

    public String name;

    public String surname;

    public Money income;

    public UserData()
    {
        this.pesel = "";
        this.uuid = "";
        this.name = "";
        this.surname = "";
        this.income = new Money();
    }

    public UserData(String pesel, String uuid, String name, String surname, Money income)
    {
        this.pesel = pesel;
        this.uuid = uuid;
        this.name = name;
        this.surname = surname;
        this.income = income;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        UserData r = null;
        if(rhs instanceof UserData)
        {
            r = (UserData)rhs;
        }

        if(r != null)
        {
            if(this.pesel != r.pesel)
            {
                if(this.pesel == null || r.pesel == null || !this.pesel.equals(r.pesel))
                {
                    return false;
                }
            }
            if(this.uuid != r.uuid)
            {
                if(this.uuid == null || r.uuid == null || !this.uuid.equals(r.uuid))
                {
                    return false;
                }
            }
            if(this.name != r.name)
            {
                if(this.name == null || r.name == null || !this.name.equals(r.name))
                {
                    return false;
                }
            }
            if(this.surname != r.surname)
            {
                if(this.surname == null || r.surname == null || !this.surname.equals(r.surname))
                {
                    return false;
                }
            }
            if(this.income != r.income)
            {
                if(this.income == null || r.income == null || !this.income.equals(r.income))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::Bank::UserData");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, pesel);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, uuid);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, name);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, surname);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, income);
        return h_;
    }

    public UserData clone()
    {
        UserData c = null;
        try
        {
            c = (UserData)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.pesel);
        ostr.writeString(this.uuid);
        ostr.writeString(this.name);
        ostr.writeString(this.surname);
        Money.ice_write(ostr, this.income);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.pesel = istr.readString();
        this.uuid = istr.readString();
        this.name = istr.readString();
        this.surname = istr.readString();
        this.income = Money.ice_read(istr);
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, UserData v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public UserData ice_read(com.zeroc.Ice.InputStream istr)
    {
        UserData v = new UserData();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<UserData> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, UserData v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<UserData> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(UserData.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final UserData _nullMarshalValue = new UserData();

    /** @hidden */
    public static final long serialVersionUID = 2015984275985198686L;
}
